### ISSUE TITLE
error: User mmdbalkhi not Found

### ISSUE THREAD

**Issue by mmdbalkhi** [solstice23/osu-stats-signature#2]
Hi, this is very cool, but unfortunately, I can not make it. Says my username is not founded

link: https://osu-sig.vercel.app/card?user=mmdbalkhi&mode=std&lang=en&animation=true&hue=268
![screenshot](https://user-images.githubusercontent.com/65954744/157892619-202f1ad4-a837-41de-b7cf-55877281bf1f.png)

**Comment by chikof** [comment]
Are you sure your username is correct?

https://user-images.githubusercontent.com/53100578/157958438-b802ac57-9997-4c15-9e43-1961068066a8.mp4

**Comment by solstice23** [comment]
There is no user called `mmdbalkhi`. https://osu.ppy.sh/users/mmdbalkhi

**Comment by mmdbalkhi** [comment]
eh. Sorry I thought this was something like https://github.com/lowlighter/metrics but it's something else!

**Comment by chikof** [comment]
~~They are just your osu! stats, you can put them in your Github profile too.
Is not very different~~

Nvm, I think I just understood what you meant.
