### ISSUE TITLE
[Feature Request] Addition of osu!Skills data

### ISSUE THREAD

**Issue by TheFantasticLoki** [solstice23/osu-stats-signature#4]
I love what you have made here and it's very high quality, but I do have an idea for a potential toggle for the cards. Would it be possible to get the data from osu!Skills ([My Profile as an example](https://osuskills.com/user/Fantastic%20Loki)) and integrate that into the playercards? I used to use another playercard generator thing but I can't remember what I used and yours is better but it had similar style skill meters. Here is the last card I generated to show what I mean: 
![image](https://user-images.githubusercontent.com/26889568/184864870-af37abf0-07d7-4e52-b83a-e419575672d1.png)

Would this be possible at all?

**Comment by solstice23** [comment]
Seems possible, there are two ideas I can think of so far: 
1. Replace the current figures for player statistics (like total ranked score) with the skills data
2. Add a new card type, which contains the data  in your example

Also, I suppose that using a hexagonal radar chart is better than the bar chart because it takes less area and is more distinct to read. Some aspects of skills like memory should be optional to hide too.

**Comment by TheFantasticLoki** [comment]
I like the second option better as it allows people to not use it if they don't want it. I also like the idea of having the hexagonal design as an option but for default you could have it just under the current design as an addon like the design in the pic above.

**Comment by solstice23** [comment]
I am trying to make a sketch, and there is a problem. If the chart is a hexagon, it is easy to put all the labels beside it. But if it is a heptagon, there are not enough spaces to put them, also the asymmetrical shape makes labels look very strange. So always hiding the "memory" might be a good choice.

![image](https://user-images.githubusercontent.com/23134847/184896884-159f62c7-76b9-444e-9fe3-276447fe1ee9.png)

**Comment by TheFantasticLoki** [comment]
Mmm I think hiding memory would be fine if you gave an option to replace another label with memory. Cause then FL players are also satisfied. Maybe reaction since you don't really utilize it for a memorized play.

**Comment by TheFantasticLoki** [comment]
Also in the same space you have the hexagon you could have another option to show your global ranking for that skill like it shows on osu!skills. They would be seperate from each other tho since same space.

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/184909371-7711a3fa-dfbb-4eec-abfb-81d5d02e57c1.png)

This is what will happen if we put a heptagon here, seems a bit weird and there is no space to show the value or rank of every item. I think a bar diagram for 7 aspects would be better(keep the radar chart for 6 aspects)?

**Comment by TheFantasticLoki** [comment]
def no heptagon I think my idea of replacing reaction with memory as an option is better and then also having the bar diagram as another option. Maybe show global rankings for the skills on bar diagram since should be somewhat easy to fit on say the right side like on the website.

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/184934191-f8050f81-9aa0-45cf-a11b-14f14e48dbb3.png)

Not so harmonious..., visually. Any suggestions?

**Comment by TheFantasticLoki** [comment]
yea copy and scale the outer hexagon down and make layers like a graph and then fill in the center portion with  something with an alpha of like 70

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/184937099-b3477394-e145-4499-b22d-d8ec900694d3.png)

What about this

**Comment by TheFantasticLoki** [comment]
mmmm so like what would the scaling be like outer ring should be 1k but then next ring is what 500 or is it 666 is the first inner ring the starting point or?
Other than that it's looking good but I think the yellow should be like bright pink like above playcount so it matches theme

**Comment by solstice23** [comment]
Currently I am dividing them into 1/3 (666). The images below show two cases (666 and 725). I think the latter one is too dense. 

![image](https://user-images.githubusercontent.com/23134847/184938613-ccd6466e-ad9b-4a59-8289-0b8e8f30e631.png)
![image](https://user-images.githubusercontent.com/23134847/184938519-c82d20d1-c860-4b9d-bfb9-1b53e3ea0e25.png)

**Comment by TheFantasticLoki** [comment]
The latter ig isn't too bad but I think it could be the very center point is 0 then first ring is 250 and so on till 1k or you could just use the first example one and have the first ring be start point and middle ring be 500 but that would leave a fair amount of guess work.
Also maybe have divider lines for each of the verticies down to the center point for easier reading and make the center rings a little bit more transparent

**Comment by TheFantasticLoki** [comment]
cause the center rings are not supposed to be super legible just enough to have a general idea of the scale of each value. So if they are a bit more transparent I don't think you'll have too much of a cluttering problem but I digress

**Comment by solstice23** [comment]
My original plan is to add figures for every aspect, I will do this later, don't know if there is enough space.

Reducing opacity on some rings can make this looks better:

![image](https://user-images.githubusercontent.com/23134847/184940817-209b2009-b4ac-455f-b0f8-ded82ebb94e5.png)

**Comment by TheFantasticLoki** [comment]
Oh I like that a lot it makes a clear definition of what the halfway marker or 500 is and does reduce the clutter a fair bit like I thought. But I still think some sectioning lines would be useful. even if you make them like dotted and lower opacity

**Comment by TheFantasticLoki** [comment]
Btw Solstice is there any chance we could discord call I am very VERY curious as to how you are achieving all this. My discord user is: The Fantastic Loki#0671

**Comment by solstice23** [comment]
Discord friend request sent

**Comment by solstice23** [comment]
The new version with osu!skills has been deployed. You can toggle the chart by switching these options.

![image](https://user-images.githubusercontent.com/23134847/185061202-93a7a95f-fe3c-4296-bdae-d57c76212918.png)

**Comment by solstice23** [comment]
Completed
